# -*- coding: utf-8 -*-
"""PRATIKUM PK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dQzBY5TqhY_IGcgXl9Dt5fzu73h_lSa7

# PERTEMUAN 2
"""

="Ananta"nama
umur=19
ipk=3,6
nilai=[50,70,100]
hobi=("basket","game")
mobil={'mobil mobilan':'merah'}

print(nama,type(nama))
print(umur,type(umur))
print(ipk,type(ipk))
print(nilai,type(nilai))
print(hobi,type(hobi))
print(mobil,type(mobil))

a=int(input("a adalah"))
b=int(input("b adalah"))
penjumlahan = a + b
pengurangan = a - b
perkalian = a * b
pembagian = a / b
modulus = a % b

print("a+b=",penjumlahan)
print("a-b=",pengurangan)
print("a*b=",perkalian)
print("a/b=",pembagian)
print("a%b=",modulus)

"""OPERATOR RELASI

"""

A = 10
B = 15
print(A == B)
print(A != B)
print(A > B)
print( A < B)
print(A >= B)
print(A <= b)

"""OPERATOR:LOGIKA

"""

a = 2
b = 1
c = 5

print((a > b) and (c > b))
print((a > b) or (c > b))
print(not(b>b))

"""# PERTEMUAN 3

INPUT/OUTPU
"""

#contoh input string
nama = input("masukkan nama anda:")
print("halo,",nama)

#contoh input integer
umur = int(input("masukkan umur anda:"))
print("umur anda:",umur)

#contoh input fload
ipk = float(input("masukkan ipk anda:"))
print("ipk anda:",ipk)

"""
CONTOH INPUT YANG DI PISAHKAN SPASI"""

bil = input("masukkan dua bilangan bulat dipisahkan oleh spasi:")
bil1,bil2 = map(int,bil.split())
print("bilangan pertama:",bil1)
print("bilangan keedua:",bil2)

"""MACAM-MACAM JENIS OUTPUT

"""

print("hallo",nama,'Umur',umur,'ipk anda;',)
print('hallo'+nama+", Umur anda:", umur, "ipk anda:",ipk)
print("hallo %s, Umur anda: %i,ipk anda, ipk: %.1f" %(nama,umur,ipk))
print(f"hallo{nama},Umur anda:{umur},ipkanda:{ipk}")

"""STRUKTUR RUNTUNAN"""

#input
pi = 22/7
r = int(input("jari-jari="))
#proses menghitung luas lingkaran
luas = pi*r*r
#output luas lingkaran
print("pi = %.2f" %pi)
print("jari-jari=",r)
print("luas lingkaran=%.2f"%(luas))

"""# TUGAS PK

"""

# input
p = 12
l = int(input("lebar="))
# proses menghitung luas persegi panjang
luas = p*l
#output luas persegi panjang
print("p = 12")
print("l=", l)
print("luas persegi panjang", {luas})

#input
p = int(input("panjang="))
l = int(input("lebar="))
#proses menghitung luas persegi panjang
luas = p*l
#output luaspersegi panjang
print("p=", p)
print("l=",l)
print("luas persegi panjang", {luas})

"""# SEL PERTAMA
Mendeklarasikan variabel "p" digunakan untuk menyimpan nilai p yaitu 12. Mendeklarasikan variabel "l" yang digunakan untuk inputan dari user,dengan type data integer. 'print("P=12")' digunakan untuk menampilkan nilai atau isi dari variabel 'p'. 'print("l=", l)' menampilkan nilai atau isi dari variabel 'l', namun pada saat sel 1 varibel l harus di input agar nilai atau sistem pada program baru bisa di jalankan. 'print("luas persegi panjang", {luas})'di tampilkan untuk menampilkan variabel atau isi yang di peroleh dari variabel luas

#SEL KEDUA
pada sel kedua saya mencoba utuk bervariasi yaitu tidak menambahkan inputan nilai yang ada pada 'p' dan 'l',sehingga kita harus memasukkan nilai atau variabel itu agar program bisa berjalan
  mendeklarasikan variabel 'p' digunakan untuk menyimpan nilai 'p',karna nilai tidak ada atau belum di input maka kita harus memasukkan nilai setelah proses run di mulai
  mendeklarasikan nilai 'l' digunakan untuk menampilakan nilai atau variabel 'l',hal ini sama di lakukan dengan nilai 'p'.
  'print("P=12")' digunakan untuk menampilkan nilai atau isi dari variabel 'p'. 'print("l=", l)' menampilkan nilai atau isi dari variabel 'l', namun pada   saat sel 1 varibel l harus di input agar nilai atau sistem pada program baru bisa di jalankan. 'print("luas persegi panjang", {luas})'di tampilkan untuk menampilkan variabel atau isi yang di peroleh dari variabel luas

# PERTEMUAN 4
"""

angka = int(input("masukkan angka"))

if angka % 2 == 0:
  print(f"(angka)adalah bilangan GENAP")

tahun = int(input("masukkan tahun"))
if (tahun % 4 == 0 and tahun % 100 != 0) or (tahhun %400 == 0):
  print(f"(tahun) adlah tahun kabisat")
else:
  print(f"(tahun) bukan tahun kabisat")

tahun = int(input("masukkan tahun"))
match tahun :
  case int if (tahun % 4 == 0 and tahun % 100!=0) | (tahun % 400 == 0):
    print(f"(tahun) adalah tahun kabisat")
  case _:
    print(f"(tahun) bukan tahun kabisat)

bil1 = int(input("masukkan angka ke 1 : "))
bil2 = int(input("masukkan angka ke 2 : "))
operator = input("masukkan operator yang di inginkan(+, -, *, /)")

if operator == "+":
  hasil = bil1 = bil2
  print(f"{bil1} + {bil2} = {hasil}")
elif operator == "-":
  hasil = bil1 - bil2
  print(f"{bil1} - {bil2} = {hasil}")
elif operator == "*":
  hasil = bil1 * bil2
  print(f"{bil1} * {bil2} = {hasil}")
elif operator == "/":
  hasil = bil1 / bil2
  print(f"{bil1} / {bil2} = {hasil}")
else:
  print("operator tidak tersedia")